Quickenberg/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from books.urls import index
from django.conf.urls.static import static
from Quickenberg import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('books.api_urls', namespace='api')),
    url(r'^', include('books.urls', namespace='book_urls'))

]

# import static files

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

books/urls.py
# Metadata
__author__ = 'mgoldbas'
__date__ = '2/3/17'
__copyright__ = 'Copyright 2016 by Open Aristos, distributed under Mozilla 2.0 license.'
__license__ = 'This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.'


# Manage Resources
from books.views import index, EnterFileTextView, EnterInputTextView, EnterIDView, TextListView, EnterAuthorView\
    , EnterGenreView
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import url


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^books/$', TextListView.as_view(), name='books'),
    url(r'^id/$', EnterIDView.as_view(), name='add_id'),
    url(r'^file/$', EnterFileTextView.as_view(), name='add_file'),
    url(r'^input/$', EnterInputTextView.as_view(), name='add_input'),
    url(r'^author/$', EnterAuthorView.as_view(), name='add_author'),
    url(r'^genre/$', EnterGenreView.as_view(), name='add_genre'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

templates/author.html
{% extends 'index.html' %}
{% block body %}
        {% block body_form %}
    <form method="POST">
        <table>

            {% if message %}
             <tl>{{ message }}</tl><br>
            {% endif %}
            {% csrf_token %}

            {{ form.as_table }}
        </table>
        <button type = "submit" class = "btn btn-primary">Submit</button>
    </form>
    {% endblock %}
    {% block body_list %}
        <h3>{{ model_name }}</h3>
        <ul>
        {% for author in authors %}

        <li>{{ author.name }}</li>

        {% endfor %}
    </ul>
    {% endblock %}
{% endblock %}

templates/book_list.html
{% extends 'index.html' %}
{% block body %}

    {% block book_forms %}

        <div>
            <a href={% url 'book_urls:add_input' %}><button type = "button" class = "btn btn-primary">Enter New Text</button></a>
            <a href={% url 'book_urls:add_file' %}><button type = "button" class = "btn btn-primary">Enter New File</button></a>
            <a href={% url 'book_urls:add_id' %}><button type = "button" class = "btn btn-primary">Enter Gutenberg Book</button></a>
        </div>

    {% endblock %}

    {% block book_list %}
    <h3> Books</h3>
    <table>
    <tr>
        <th>Title</th>
        <th>Author</th>
    </tr>
    {% for book in books %}
        <tr>

        <td> {{ book.title }} </td>
        <td> {{ book.author }}</td>
        </tr>
    {% endfor %}
    </table>
    {% endblock %}
{% endblock %}

templates/form_and_list.html
{% extends 'index.html' %}
{% block body %}
    {% block body_form %}
    <form method="POST">
        <table>

            {% if message %}
             <tl>{{ message }}</tl><br>
            {% endif %}
            {% csrf_token %}

            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
    {% endblock %}

    {% block body_list %}

    <ul>
        {% for item in list %}

        <li>{{ item }}</li>

        {% endfor %}
    </ul>
    {% endblock %}
{% endblock %}

templates/id_form.html
{% extends 'index.html' %}
{% block body %}
    <div>
    <form method="POST">
        {% if message %}
        <p>{{ message }}</p>
            <br>
        {% endif %}
         {% csrf_token %}
        <table>
        {{ form.as_table }}
                </table>



        <div class="btn-group">
            <button type = "submit" class = "btn btn-primary">Submit</button>
        </div>
    </form>
    </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../static/css/simple-sidebar.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <title>{{ title }}</title>
    {%  load static %}
</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href={% url 'book_urls:index' %}>Home</a>
                </li>
                <li>
                    <a href={% url 'book_urls:books' %}>Book List</a>
                </li>

                <li>
                    <a href={% url 'book_urls:add_id' %}>Enter Gutenberg Book</a>
                </li>
                <li>
                    <a href={% url 'book_urls:add_author' %}>Enter Author</a>
                </li>
                <li>
                    <a href={% url 'book_urls:add_genre' %}>Enter Genre</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        {% if toggle_menu %}
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                        <br>
                        {% endif %}
                        {% if messages %}
                        <ul class="messages" >
                            {% for msg in messages %}
                            <li>
                                <div class="alert alert-{{ msg.level_tag }}" role = "alert">
                                    {{ msg.message }}
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        {%  block body %}
                        <h1>{{ title }}</h1>
                        <p>This template has a responsive menu toggling system. The menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will appear/disappear. On small screens, the page content will be pushed off canvas.</p>
                        <p>Make sure to keep all page content within the <code>#page-content-wrapper</code>.</p>

                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="../static/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../static/js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>

templates/list.html
{% extends 'index.html' %}
{% block body %}
    <h3> Books</h3>
    <table>
    <tr>
        <th>Title</th>
        <th>Author</th>
    </tr>
    {% for book in books %}
        <tr>

        <td> {{ book.title }} </td>
        <td> {{ book.author }}</td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>

</body>
</html>